fragdev/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib import admin
from fragdev import views

# Register admin pages
admin.autodiscover()

urlpatterns = [
    path('',
        views.HomeView.as_view(),
        name='home'),
    path('about/',
        views.AboutView.as_view(),
        name='about'),
    path('contact/',
        TemplateView.as_view(template_name="page-contact.html"),
        name='contact'),
    path('mei2019/',
        TemplateView.as_view(template_name="page-mei2019.html"),
        name='mei2019'
    ),
    path('minecraft/',
        TemplateView.as_view(template_name="page-minecraft.html"),
        name='minecraft'
    ),
    path('resume/',
        TemplateView.as_view(template_name="page-resume.html"),
        name='resume'
    ),
#    path('hire/',
#        TemplateView.as_view(template_name="page-hire.html"),
#        name='hire'
#    ),
    path('admin/', admin.site.urls),
]

# Set up some custom url patterns for debugging
if settings.DEBUG:
    # Append static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # Append media directory
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Blog URLs
if 'wiblog' in settings.INSTALLED_APPS:

    import wiblog.urls

    urlpatterns += [
        path('blog/', include(wiblog.urls)),
    ]	


# Dynamic image URLs
if 'images' in settings.INSTALLED_APPS:

    import images.urls

    urlpatterns += [
        path('img/', include(images.urls)),
    ]	


# Project URLs
if 'projects' in settings.INSTALLED_APPS:

    import projects.urls

    urlpatterns += [
        path('projects/', include(projects.urls)),
    ]	

images/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

# Placeholder urlpatterns list, in case views are added

app_name = 'images'

urlpatterns = []

projects/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='projects'),
    path('<slug>', views.project, name='project'),
]

wiblog/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path 
from django.views.generic import TemplateView
from wiblog import feeds, views

app_name = 'wiblog'

urlpatterns = [
	path('archive/',
            views.ArchiveView.as_view(),
            name='archive'),
	path('comment/',
            views.CommentView.as_view(),
            name='comment'),
	path('comment-successful/',
            TemplateView.as_view(template_name="page-commented.html"),
            name='comment-successful'),
	path('feeds/atom/',
            feeds.PostFeedAtom(),
            name='atom'),
	path('feeds/rss/',
            feeds.PostFeedRSS(),
            name='rss'),
	path('tagged/<tag>/',
            views.TaggedPostView.as_view(),
            name='tagged'),
	path('tags/',
            views.TagsView.as_view(),
            name='tags'),
	path('<slug>',
            views.PostView.as_view(),
            name='post'),
	path('',
            views.IndexView.as_view(),
            name='index'),
]

fragdev/views.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.views.generic import TemplateView
from django.template.context_processors import csrf
from django.urls import reverse, reverse_lazy
import time


class HomeView(TemplateView):
    """
    The homepage; list the latest blog post, project, and some other
    pertinent information
    """
    template_name = 'page-home.html'

    def get_context_data(self, **kwargs):
        """
        Add latest blog post and latest project as context
        """
        context = super().get_context_data(**kwargs)

        # Get the latest blog post
        if 'wiblog' in settings.INSTALLED_APPS:
            from wiblog.models import Post

            try:
                context['post'] = Post.published.order_by('-date').first()
            except:
                pass

        # Try to get the latest project
        if 'projects' in settings.INSTALLED_APPS:
            from projects.models import Project

            try:
                projects = Project.objects.exclude(status=Project.HIDDEN)
                context['project'] = projects.order_by('-date')[0]
            except:
                pass

        return context


class AboutView(TemplateView):
    """
    About Me page
    """
    template_name = 'page-about.html'

    def get_context_data(self, **kwargs):
        """
        Calculate my age to the nearest... well, whatever
        439664400 - Dec. 7th, 1983, 11PM in UNIX time
        31536000  - Seconds in a year
        """
        context = super().get_context_data(**kwargs)
        context['age'] = (time.time() - 439664400) / 31536000 

        return context

fragdev/templates/base.html
{% load static %}
<!doctype html>
<html>

<head>
	<title>{% block title %}{% endblock %}</title>
	<meta charset="UTF-8">
	<link rel="manifest" href="{% static "fragdev/manifest.json" %}">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<link rel="icon" type="image/x-icon" href="{% static "fragdev/favicon.ico" %}">
	{% block head %}
	{% endblock %}
</head>

<body>
	{% block body %}
	{% endblock %}
</body>

</html>

fragdev/templates/layout.html
{% extends "base.html" %}
{% load static %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static "fragdev/css/layout.css" %}">
{% endblock %}
</head>

<body>
	{% block body %}
	<a href="#content" class="a11y-link">Skip to content</a>
	<header class="header">
		<div class="site-title"><a href="/">Fragmented Development</a></div>
		<nav>
			<ul class="nav boxy">
				{% include "partials/nav.html" %}
			</ul>
		</nav>
	</header>

	<main class="boxy" id="content">
		{% block content %}
		{% endblock %}
	</main>
	<nav>
		<ul class="nav">
			<li><a class="nav-item" href="{% url 'about' %}">About</a></li>
			<li><a class="nav-item" href="{% url 'wiblog:index' %}">Blog</a></li>
			<li><a class="nav-item" href="{% url 'contact' %}">Contact</a></li>
			<li><a class="nav-item" href="{% url 'projects:projects' %}">Projects</a></li>
			{#<li><a class="nav-item" href="{% url 'resume' %}">Résumé</a></li>#}
		</ul>
	</nav>
	<footer>
		© 2021, Jacob Honeyhume. The CSS/HTML/JS is released under <a href=
		"https://www.gnu.org/licenses/agpl.html">AGPLv3</a>. The typeface is <a
		href="https://www.google.com/fonts/specimen/Roboto">Roboto</a>, by
		Christian Robertson.
	</footer>
	{% endblock %}
</body>

</html>

fragdev/templates/page-about.html
{% extends "layout.html" %}
{% load static %}

{% block title %}About Jacob Honeyhume{% endblock %}

{% block content %}
		<header class="content-header">
			<h1>About Jacob Honeyhume</h1>
			<p>
				I'm {{ age }}-year old living in the central coast area of
				California, near Monterey Bay.
			</p>
		</header>
		<figure>
			<img src="{% static "/fragdev/img/windigo.jpg" %}"
				alt="An illustration of Windigo, sitting with a plate of cookies, gesticulating">
			<figcaption>illustration by Anne Hoffer</figcaption>
		</figure>
		<p>
			I am currently working at <a href="https://tylertech.com">Tyler Technologies</a>
			as a PHP Developer, but I'm open to new opportunities.
		</p>
		<p>
			I dig coffee, <a href="http://www.gnu.org/philosophy/free-sw.html">Free software</a>,
			and <a href="https://minecraft.net">Minecraft</a>.
		</p>
		<h2>Public Key</h2>
		<p>
			In case you have an interest in privacy and cryptography, you can download my <a href=
			"{% static "/fragdev/misc/windigo-public.asc" %}">public key</a> as an ASCII-armored text file, or you can
			simply fetch it from your favorite keyserver. My key ID is
			<strong><code>0xDAECFD4CBCC76ED6</code></strong>.
		</p>
		<h2>Fragmented Development</h2>
		<p>
			<strong>Fragmented Development</strong> was originally started as a Web Design company,
			going by the name of Wednesday Bubbles. While mildly successful in it's
			own small way, WB had several problems; first, the general public cannot
			spell Wednesday. Also, it's very hard to gain respect with a name that
			includes the word "Bubbles" in it. So, I did an informal poll on my blog, and Fragmented
			Media won out. This didn't last long, simply because the "Media" attatchment was much too
			restrictive, and didn't really reflect what we could do. So, in late 2003 the name was
			changed one final time to Fragmented Development, and the domain was registered in early
			2004.
		</p>
		<p>
			After a couple reorganizations and different groupings, <strong>Fragmented
			Development</strong> has become my personal website, where I host a small basketfull of
			Free software applications.
		</p>
{% endblock %}

fragdev/templates/page-contact.html
{% extends "layout.html" %}
{% block title %}Contact Me{% endblock %}
{% block content %}
		<header class="content-header">
			<h1>Contact Me</h1>
			<p>
				I accept questions, comments, or ASCII art postcards.
			</p>
		</header>
		<main>
			<h1>Email</h1>
			<p>
				You can email me at <span id="contact-email" data-user="jacob"
					data-domain="fragdev.com">jacob, the at symbol, then
					fragdev dot com</span>. I accept
				encrypted emails: you can use <a href="/static/misc/windigo-public.asc"
				>my public key</a> (<strong><code>0xDAECFD4CBCC76ED6</code></strong>).

			</p>
			<h1>Other</h1>
			<p>
				I prefer email. If you have my phone number, I accept phone
				calls, but not texts. If you happen to find me in California,
				feel free to say hello.
			</p>
			<p>
				I very occasionally log onto <a href="https://libera.chat">libera.chat</a>.
			</p>
			<p>
				I don't use any social media, and nobody else should either.
			</p>
		</main>
		<script language="javascript">
            const emailSpan = document.getElementById('contact-email');
            const address = emailSpan.dataset.user + '@' +
                emailSpan.dataset.domain;

            emailSpan.innerHTML = '<a href="mailto:' + address + '">' + address
                + '</a>';
        </script>
{% endblock %}

fragdev/templates/page-home.html
{% extends "layout.html" %}

{% load static %}

{% block title %}Fragmented Development{% endblock %}

{% block head %}
	{{ block.super }}
	<link rel="openid2.provider" href="https://id.fragdev.com"/>
	<link rel="openid2.local_id" href="https://fragdev.com"/>
	<link rel="openid.server" href="https://id.fragdev.com"/>
	<link rel="openid.delegate" href="https://fragdev.com"/>
{% endblock %}

{% block content %}
		<section class="home-modules">

			{% if post %}
			<article>
				<h1>Latest Post</h1>
				<h2>
					<a href="{% url 'wiblog:post' post.slug %}">{{ post.formatted_title }}</a>
				</h2>
				{{ post.formatted_summary }}
				<p>
					Read the full post: <a href=
					"{% url 'wiblog:post' post.slug %}">{{ post.formatted_title }}</a>
				</p>
			</article>
			{% endif %}

			{% if project %}
			<article>
				<h1>Current Project</h1>
				<h2>
					<a href="{% url 'projects:project' project.slug %}">{{ project.name }}</a>
				</h2>
				{% if project.short_desc %}
				<p>
					{{ project.short_desc }}
				</p>
				{% endif %}
				{% if project.thumbnail %}
				<p>
					<a href="{% url 'projects:project' project.slug %}"><img
					src="{{ project.thumbnail.get_absolute_url }}" width="100%"
					alt="{{ project.thumbnail.desc }}"></a>
				</p>
				{% endif %}
			</article>
			{% endif %}

			<article>
				<h1>Web Applications</h1>
				<p>
					I run the following <abbr title=
					"free, libre, open source software">FLOSS</abbr> software:
				</p>
				<ul>
					<li>Mumble (mumble.fragdev.net)</li>
					<li>
						<a href="https://cloud.fragdev.com">Nextcloud</a>
					</li>
					<li>
						<a href="https://mail.fragdev.com">Roundcube</a>
					</li>
					<li>
						<a href="https://links.fragdev.com">SemanticScuttle</a>
					</li>
					<li>
						<a href="https://ttrss.fragdev.com">Tiny Tiny RSS</a>
					</li>
				</ul>
				<p>
					If you would like an account on any of these services, feel
					free to <a href="/contact">contact me</a>.
				</p>
			</article>

			<article>
				<h1>Platform</h1>
				<p>
					My servers run a host of underlying software that allows me to host sites
					and applications:
				</p>
				<ul class="home-software-list">
					<li>Debian GNU/Linux</li>
					<li>PHP</li>
					<li>Python</li>
					<li>Django</li>
					<li>Nginx</li>
					<li>OpenSSH</li>
					<li>MariaDB</li>
					<li>Postgres</li>
					<li>Postfix</li>
					<li>Dovecot</li>
					<li>SpamAssassin</li>
					<li>SQLite</li>
				</ul>
			</article>

		</section>
{% endblock %}

fragdev/templates/page-mei2019.html
{% extends "layout.html" %}
{% load static %}
{% load images %}

{% block title %}2019 Mei Recap{% endblock %}

{% block head %}
	{{ block.super }}
	<style type="text/css">
		.gallery {
			display: flex;
			flex-wrap: wrap;
			display: grid;
			grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
			grid-auto-rows: minmax(150px, auto);
			grid-gap: 1em;
		}

		.gallery-item {
			display: flex;
			align-items: center;
			justify-content: center;
			  
			/* Flex Fallback */
			margin-left: 5px;
			margin-right: 5px;
			flex: 1 1 200px;
		}

		@supports (display: grid) {
			.gallery-item {
				margin: 0;
			}
		}
	</style>
{% endblock %}

{% block content %}
		<header class="content-header">
			<h1>2019 Mei Recap</h1>
			<p>
				I'm terrible at keeping up with these updates… so, photo dump!
			</p>
		</header>
		<div class="gallery">
			<div class="gallery-item">
				{% image_thumbnail "august-2018-birthday-celebration" %}
			</div>
			<div class="gallery-item">
				{% image_thumbnail "october-2019-hat" %}
			</div>
			<div class="gallery-item">
				{% image_thumbnail "september-2019-fall-festival" %}
			</div>
			<div class="gallery-item">
				{% image_thumbnail "september-2019-group-shot" %}
			</div>
			<div class="gallery-item">
				{% image_thumbnail "october-2019-fashionable" %}
			</div>
			<div class="gallery-item">
				{% image_thumbnail "september-2019-beach" %}
			</div>
			<div class="gallery-item">
				{% image_thumbnail "october-2019-mmmm" %}
			</div>
			<div class="gallery-item">
				{% image_thumbnail "october-2019-face-push" %}
			</div>
			<div class="gallery-item">
				{% image_thumbnail "december-2019-christmas-morning" %}
			</div>
		</div>
{% endblock %}

fragdev/templates/page-minecraft.html
{% extends "base.html" %}
{% load static %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static "fragdev/css/minecraft.css" %}">
{% endblock %}

{% block body %}
	<main id="content" class="map-overlay">
		<h1>Minecraft</h1>
		<p>
			This is my Minecraft world. I spend a lot of time here, and thought
			it might be interesting to let others take a look around. Enjoy!
		</p>
	</main>
	<iframe class="map" src="http://cohen.fragdev.net"></iframe>
{% endblock %}

fragdev/templates/page-resume.html
{% extends "layout.html" %}

{% block title %}Jacob Honeyhume{% endblock %}

{% block content %}
		<header class="content-header">
			<h1>Jacob Honeyhume</h1>
			<p>
				A web developer focused on progressive enhancement, performance,
				usability, and <abbr title="free libre open source software">FLOSS</abbr> software
			</p>
		</header>
		<aside>
			<p>
				I'm currently looking for full-time employment.
				Feel free to <a href="{% url 'contact' %}">contact me</a>!
			</p>
		</aside>
		<h2>Web Development Skills</h2>
		<p>
			I have many public examples of my work and contributions listed on
			the <a href="{% url 'contact' %}">Projects</a> page and social coding
			sites like <a href="https://github.com/lo-windigo">GitHub</a> and
			<a href="https://gitlab.com/u/windigo">Gitlab</a>.
		</p>
		<ul>
			<li>
				<strong>Python:</strong> Five years of experience using Python
				with WSGI and web frameworks like Django (including Oscar
				Commerce, Mezzanine) and Flask
			</li>
			<li>
				<strong>PHP:</strong> Fifteen years of experience writing custom
				PHP applications, including:
				<ul>
					<li>
						A framework to support a site with thousands of pages
						and dozens of related but independent layouts
					</li>
					<li>
						Integrating external systems and data sources, some
						without APIs
					</li>
					<li>
						Feature development and systems integrations
					</li>
				</ul>
			</li>
			<li>
				<strong>SQL:</strong> Fifteen years of experience writing SQL
				for different database variants, such as (in order of
				familiarity): MySQL/MariaDB, Microsoft SQL Server, Postgres,
				and SQLite
			</li>
			{
			<li>
				<strong>HTML:</strong> Twenty years of using the latest HTML
				techniques to create usable, accessible, fast and light pages.
				Very familiar with responsive/progressive design techniques
			</li>
			<li>
				<strong>CSS:</strong> Twenty years of experience writing CSS in
				a modular, reusable fashion, with performance and speed as
				priorities
			</li>
		</ul>
		<h2>Server Skills</h2>
		<p>
			I have years of experience running my own servers and managing
			networks, including the following:
		</p>
		<ul>
			<li>
				<strong>Server Software:</strong> Nginx, MariaDB and MySQL,
				Postgres, Postfix, Dovecot, SpamAssassin, SQLite, UWSGI
			</li>
			<li>
				<strong>Linux Platform:</strong> Primarily Debian and
				Ubuntu systems
			</li>
			<li>
				<strong>Configuration Management:</strong> Experience
				automating and deploying servers across different cloud
				providers with Ansible
			</li>
		</ul>
		<h2>Work Experience</h2>
		<ul>
			<li>
				<p>
					<strong>Freelance/Consulting:</strong> 2002-Present
				</p>
				<p>
					The majority of my consulting has been web design and development, from simple static sites to full e-commerce solutions, for which I provide hosting and email services.
				</p>
				<p>
					I have also provided general technical support for businesses like Sea Ranch Vacation Rentals and Capital North Advisors, working directly with users.
				</p>
			</li>
			<li>
				<p>
					<strong>Instructor:</strong> Arena Tech Center, 2014-2016
				</p>
				<p>
					Instructors assisted visitors (from children to seniors) in utilizing technology;  computers, printers, software, and a recording studio with mixing board.
				</p>
			</li>
			<li>
				<p>
					<strong>IT Manager/Network Administrator:</strong> Garcia River Casino, 2014-2016
				</p>
				<p>
					The Garcia River Casino has six separate networks that must be isolated, yet need to share common resources – all of which is audited annually.
				</p>
				<p>
					I was also responsible for the restaurant point-of-sale system, Sage accounting, and the casino management system. I managed desktop computers, point-of-sale terminals, and taught myself to administer the VoIP phone system.
				</p>
			</li>
			<li>
				<p>
					<strong>Web/Intranet Developer:</strong> Warren County, NY, 2004-2014
				</p>
				<p>
					I was able to foster Warren County’s growth from a dozen-paged website to having several thousand documents and most departments represented on-line. Working with civil servants, politicians and community members, I made information and forms available that were previously only manually available.
				</p>
				<p>
					After moving to California, I stayed on as a remote consultant with the
					County for more than a year until they were able to find a suitable
					replacement.
				</p>
			</li>
		</ul>
		<aside>
			<p>
				The full details of my references have not been included to
				protect the privacy of my friends and colleagues, but are 
				available upon request.
			</p>
		</aside>
{% endblock %}

fragdev/templates/page-services.html
{% extends "layout.html" %}

{% block title %}Services{% endblock %}

{% block content %}
			<h1>Services</h1>
			<p>
				
			</p>
			<h2>Basic Informational Websites</h2>
			<p>
				A basic website, custom designed for your business or organization.
				Informational websites contain information that does not change
				frequently. These websites often contain:
			</p>
			<ul>
				<li>Explanations of what your business/organization does</li>
				<li>Hours of operation</li>
				<li>Address and directions</li>
				<li>Contact information and/or a contact form</li>
				<li>
					Simple "product" information
					<ul>
						<li>Restaurant menus</li>
						<li>Programming offerings or available services</li>
						<li>Brands carried</li>
					</ul>
				</li>
				<li>Staff or faculty listing</li>
			</ul>
			<h2>Dynamic Websites</h2>
			<p>
				If your organization has a need for a website with fast-moving content,
				we can help. Whether your website needs a few dynamic pages, or you
				require a full content management system, we can provide an easy to use
				way to keep your own website up to date. Features of dynamic websites
				include:
			</p>
			<ul>
				<li>Organizational or specialized blogs</li>
				<li>Photo galleries with user submissions</li>
				<li>Product catalogs that change frequently</li>
				<li>Shopping Carts</li>
				<li>User comments</li>
				<li>Pages can be changed, added or removed easily</li>
			</ul>
			<h2>Custom Development</h2>
			<p>
				We have experience developing in several languages and frameworks. If
				you require a custom plugin for your <abbr title=
				"content management system">CMS</abbr>, web integration with legacy
				in-house software, or features added to an open source project that your
				organization uses, we can help.
			</p>
{% endblock %}

{% block ancillary %}
			<h1>Free Consultation</h1>
			<p>
				If you are unsure of what you need, or you need clarification regarding
				the services we offer, please <a href="{% url 'contact' %}">contact
				us</a> for a free consultation. When in doubt, get in touch; it can't
				hurt to ask!
			</p>
			<p>
				After a consultation, we can provide quotes or estimates for projects if desired.
			</p>
{% endblock %}