fragdev/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib import admin
from fragdev import views

# Register admin pages
admin.autodiscover()

urlpatterns = [
    path('',
        views.HomeView.as_view(),
        name='home'),
    path('about/',
        views.AboutView.as_view(),
        name='about'),
    path('contact/',
        TemplateView.as_view(template_name="page-contact.html"),
        name='contact'),
    path('mei2019/',
        TemplateView.as_view(template_name="page-mei2019.html"),
        name='mei2019'
    ),
    path('minecraft/',
        TemplateView.as_view(template_name="page-minecraft.html"),
        name='minecraft'
    ),
    path('resume/',
        TemplateView.as_view(template_name="page-resume.html"),
        name='resume'
    ),
#    path('hire/',
#        TemplateView.as_view(template_name="page-hire.html"),
#        name='hire'
#    ),
    path('admin/', admin.site.urls),
]

# Set up some custom url patterns for debugging
if settings.DEBUG:
    # Append static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # Append media directory
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Blog URLs
if 'wiblog' in settings.INSTALLED_APPS:

    import wiblog.urls

    urlpatterns += [
        path('blog/', include(wiblog.urls)),
    ]	


# Dynamic image URLs
if 'images' in settings.INSTALLED_APPS:

    import images.urls

    urlpatterns += [
        path('img/', include(images.urls)),
    ]	


# Project URLs
if 'projects' in settings.INSTALLED_APPS:

    import projects.urls

    urlpatterns += [
        path('projects/', include(projects.urls)),
    ]	

images/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

# Placeholder urlpatterns list, in case views are added

app_name = 'images'

urlpatterns = []

wiblog/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path 
from django.views.generic import TemplateView
from wiblog import feeds, views

app_name = 'wiblog'

urlpatterns = [
	path('archive/',
            views.ArchiveView.as_view(),
            name='archive'),
	path('comment/',
            views.CommentView.as_view(),
            name='comment'),
	path('comment-successful/',
            TemplateView.as_view(template_name="page-commented.html"),
            name='comment-successful'),
	path('feeds/atom/',
            feeds.PostFeedAtom(),
            name='atom'),
	path('feeds/rss/',
            feeds.PostFeedRSS(),
            name='rss'),
	path('tagged/<tag>/',
            views.TaggedPostView.as_view(),
            name='tagged'),
	path('tags/',
            views.TagsView.as_view(),
            name='tags'),
	path('<slug>',
            views.PostView.as_view(),
            name='post'),
	path('',
            views.IndexView.as_view(),
            name='index'),
]

wiblog/models.py
#
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

import re
from commonmark import commonmark
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.utils.timezone import now
from wiblog import choices, managers
from images.models import Image


class Tag(models.Model):
    """
    A category of post or other object
    """
    desc = models.SlugField('Tag', max_length=50, unique=True)

    def __str__(self):
        return self.desc

    def get_absolute_url(self):
        return reverse("wiblog:tags", args=[self.desc])


class Post(models.Model):
    """
    A single blog post
    """
    DFT = choices.PostChoices.DFT
    PUB = choices.PostChoices.PUB
    PUBLISH_STATUS = choices.PostChoices.PUBLISH_STATUS
    body = models.TextField()
    date = models.DateTimeField(default=now)
    updated = models.DateTimeField(blank=True, null=True)
    slug = models.SlugField(max_length=150)
    status = models.CharField(max_length=9,
            choices=PUBLISH_STATUS)
    tags = models.ManyToManyField(Tag,
            blank=True)
    title = models.CharField(max_length=150)

    # Define model managers
    objects = models.Manager() 
    published = managers.PublishedPostManager()

    def __str__(self):
        """
        Use the post title to represent the object in the admin section
        """
        return self.title

    def get_absolute_url(self):
        """
        Use the post title to represent the object in the admin section
        """
        return reverse("wiblog:post", args=[self.slug])

    def format(self, markdown):
        """
        Format markdown into HTML, including custom image tags
        """
        tags = []

        # Find all instance of the dynamic image markdown
        for tag in re.finditer(r'\[I:([\w-]+)\]', markdown):

            tag_slug = tag.group(1)

            try:
                image = Image.objects.get(slug=tag_slug)
                tag_dict = dict()

                tag_dict['start'] = tag.start()
                tag_dict['end'] = tag.end()
                tag_dict['image'] = image

                tags.append(tag_dict)

            except ObjectDoesNotExist:
                pass

        # Replace all of the tags with actual markdown image tags, backwards, to
        # prevent changing string positions and messing up substitution
        for tag_dict in reversed(tags):

            markdown = markdown[:tag_dict['start']] + \
                '![{}]({})'.format(tag_dict['image'].desc,
                        tag_dict['image'].get_absolute_url()) + \
                markdown[tag_dict['end']:]

        return mark_safe(commonmark(markdown))


    def format_line(self, markdown):
        """
        Renders a single line of markdown as HTML without inserting it into a
        paragraph tag
        """
        html = self.format(markdown)

        if html.startswith('<p>'):
            html = html[3:]

        if html.endswith('</p>\n'):
            html = html[:-5]

        return mark_safe(html)


    def comments(self):
        """
        Only return moderated comments that apply to this post
        """
        return Comment.approved.filter(post=self.pk)


    @property
    def formatted(self):
        """
        Return the rendered post body
        """
        return self.format(self.body)


    @property
    def formatted_summary(self):
        """
        Return a rendered post summary
        """

        # FIX: For some reason, CRLF line endings are getting into Post data??
        post_text = self.body.replace("\r", "")

        # Get the first paragraph of text, and format that
        try:
            summary = post_text[:post_text.index("\n\n")]
        except ValueError:
            summary = post_text

        return self.format(summary)


    @property
    def formatted_title(self):
        """
        Return the rendered post body
        """
        return self.format_line(self.title)


    def save(self, show_updated=True):
        """
        Override the save method to do a bunch of sensible stuff, like setting
        default field values and setting up the slug field
        """

        # Default slug: just slugify the title
        if not self.slug:
            self.slug = slugify(self.title)

        # Update the updated time, if this is an existing object
        if self.id and show_updated:
            self.updated = now()

        # Call the actual save method
        super().save()


class Comment(models.Model):
    """
    Comments - Other people's input on posts
    """
    HAM = choices.CommentChoices.HAM
    SPM = choices.CommentChoices.SPM
    UNK = choices.CommentChoices.UNK
    MOD_STATUS = choices.CommentChoices.MOD_STATUS
    comment = models.TextField()
    name = models.CharField(max_length=150)
    date = models.DateTimeField(auto_now_add=True)
    moderated = models.CharField(choices=MOD_STATUS,
            default=UNK,
            max_length=14)
    post = models.ForeignKey(Post, models.CASCADE)
    url = models.URLField(blank=True,
            null=True)

    # Define model managers
    objects = models.Manager() 
    approved = managers.ApprovedCommentsManager()

    def __str__(self):
        """
        Provide a decent representation for the admin section
        """
        return '{}: {}'.format(self.name, self.comment[:75])

    def format(self, markdown):
        """
        Format markdown into HTML
        """
        return mark_safe(commonmark(markdown))

    @property
    def formatted(self):
        """
        Return the rendered comment body
        """
        return self.format(self.comment)

wiblog/forms.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django import forms
from fragdev.util.validate_ham import ANTI_SPAM, validate_ham
from wiblog import models


class CommentForm(forms.ModelForm):
    """
    Allow visitors to leave comments
    """
    verify = forms.CharField(label='Anti-spam: Type in the word "{}"'\
        .format(ANTI_SPAM),
        validators=[validate_ham],
        max_length=len(ANTI_SPAM))

    class Meta:
        model = models.Comment
        fields = ('name', 'url', 'comment', 'post')
        widgets = {
                'post': forms.HiddenInput()
                }

wiblog/views.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

import smtplib
from email.mime.text import MIMEText
from django.conf import settings
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
from django.template.context_processors import csrf
from django.views import generic 
from django.views.generic import edit
from wiblog import forms, models


class IndexView(generic.ListView):
    """
    Blog index: Show a list of the most recent posts
    """
    context_object_name = 'posts'
    paginate_by = 5
    queryset = models.Post.published.order_by('-date')
    template_name = 'base-wiblog.html'


class ArchiveView(generic.ListView):
    """
    An archival listing of all public posts
    """
    context_object_name = 'posts'
    queryset = models.Post.published.all()
    template_name = 'page-archive.html'


class CommentView(edit.CreateView):
    """
    Processing comments
    """
    form_class = forms.CommentForm
    model = models.Comment
    success_url = reverse_lazy('wiblog:comment-successful')
    template_name = 'page-comment.html'

    def form_valid(self, form):
        """
        If handling a valid form, make sure to email a notification to someone
        who can moderate it
        """
        sender = settings.CONTACT_SENDER
        sendee = settings.CONTACT_EMAIL

        msg = MIMEText('New Comment')
        msg['Subject'] = 'Comments awaiting moderation'
        msg['From'] = sender
        msg['To'] = sendee

        mailServer = smtplib.SMTP('localhost')
        mailServer.sendmail(sender, [sendee], msg.as_string())
        mailServer.quit

        return super().form_valid(form)


class PostView(generic.DetailView):
    """
    A single blog post
    """
    context_object_name = 'post'
    model = models.Post
    template_name = 'page-post.html'

    def get_context_data(self, **kwargs):
        """
        Add a comment form to the default context
        """
        context = super().get_context_data(**kwargs)

        # Send in a comment form
        context['comment_form'] = forms.CommentForm(initial={
            'post': self.object.pk,
            })

        return context


class TagsView(generic.ListView):
    """
    Display any blog tags that have been defined
    """
    context_object_name = 'tags'
    queryset = models.Tag.objects.order_by('desc')
    template_name = 'page-tags.html'


class TaggedPostView(generic.DetailView):
    """
    Show any posts that are associated with a tag
    """
    context_object_name = 'tag'
    model = models.Tag
    slug_field = 'desc'
    slug_url_kwarg = 'tag'
    template_name = 'page-tagged.html'

wiblog/templates/base-wiblog.html
{% extends "layout.html" %}
{% load static %}


{% block title %}Blog{% endblock %}

{% block head %}
	{{ block.super }}
	<link href="{% url "wiblog:atom" %}" rel="alternate" type="application/atom+xml"
		title="Fragmented Development Blog (Atom)">
	<link href="{% url "wiblog:rss" %}" rel="alternate" type="application/rss+xml"
		title="Fragmented Development Blog (RSS)">
	<link rel="stylesheet" type="text/css"
		href="{% static "/wiblog/css/prism.css" %}">
	<script type="text/javascript"
		 src="{% static "/wiblog/js/prism.js" %}"></script>
{% endblock %}

{% block content %}
			<header class="content-header">
				{% include "partial-nav.html" %}
				<h1>Blog</h1>
				<p>
					This is a repository for the thoughts, notes, and achievements
					of <strong>Mr. Jacob Honeyhume</strong>. It contains posts on a large variety of
					subjects, technical and otherwise.
				</p>
			</header>
			<hr>
			{% for post in posts %}
			<article>
				<header class="post-header">
					<h1 class="post-title">
						<a href="{% url "wiblog:post" slug=post.slug %}">
							{{ post.formatted_title }}</a>
					</h1>
					<p class="post-date">
						Posted on {{ post.date|date:"Y-m-d" }}
						{% if post.updated > post.date %}
						(Updated on {{ post.updated|date:"Y-m-d" }})
						{% endif %}
					</p>
				</header>
				{{ post.formatted_summary }}
				<ul class="tag-list">
					{% for tag in post.tags.all %}
						<li>
							<a href="{% url "wiblog:tagged" tag %}" class="tag">{{ tag }}</a>
						</li>
					{% endfor %}
				</ul>
			</article>
			{% endfor %}

			<hr>
			{% if is_paginated %}
			<nav role="navigation" aria-label="Pagination Navigation">
				<ul class="sub-nav">
					{% if page_obj.has_previous %}
					<li>
						<a href="{% url "wiblog:index" %}?page={{ page_obj.previous_page_number }}"
							class="nav-item pagination-prev">Newer Posts</a>
					</li>
					{% endif %}
					{% if page_obj.has_next %}
					<li>
						<a href="{% url "wiblog:index" %}?page={{ page_obj.next_page_number }}"
							class="nav-item pagination-next">Older Posts</a>
					</li>
					{% endif %}
				</ul>
			</nav>
			{% endif %}
			<p>
				For a full list of posts, feel free to check out the <a
				href="{% url "wiblog:archive" %}">Archive</a>!
			</p>
{% endblock %}

wiblog/templates/page-archive.html
{% extends "base-wiblog.html" %}


{% block title %}Archive{% endblock %}


{% block content %}
		<header class="content-header">
			{% include "partial-nav.html" %}
			<h1>Ye Olde Archive</h1>
			<p>
				A chronological listing of all of the blog posts to date.
			</p>
		</header>
		{% if posts|length %}

		{% regroup posts.all|dictsortreversed:"date.year" by date.year as yearPosts %}

		{% for year in yearPosts %}
		<h2>{{ year.grouper }}</h2>
		<ul>
			{% for post in year.list reversed %}
			<li>
				{{ post.date|date:"F jS" }}: <a href=
					"{% url "wiblog:post" post.slug %}">{{ post.formatted_title }}</a>
			</li>
			{% endfor %}
		</ul>
		{% endfor %}
		{% else %}
		<p>
			It appears that there is no content to peruse at the moment! Not to
			worry, I'm sure that if you return later this page will be full of
			dusty posts that you can pick up and enjoy.
		</p>
		{% endif %}
{% endblock %}

wiblog/templates/page-comment.html
{% extends "base-wiblog.html" %}


{% block title %}{{ post.formatted_title }}{% endblock %}


{% block content %}
		<header class="content-header">
			{% include "partial-nav.html" %}
			<h1>Comment</h1>
		</header>
		<h2 id="add-comment">Add Your Comment</h2>
		<form method="post" action="{% url "wiblog:comment" %}">
			{% csrf_token %}
			{{ form.non_field_errors }}
			<p>
				{{ form.post }}
				{{ form.name.errors }}
				<label for="id_name">
					{{ form.name.label }}:<br>
					{{ form.name }}
				</label>
			</p>
			<p>
				{{ form.url.errors }}
				<label for="id_url">
					{{ form.url.label }}:<br>
					{{ form.url }}
				</label>
			</p>
			<p>
				{{ form.comment.errors }}
				<label for="id_comment">
					{{ form.comment.label }}:<br>
					{{ form.comment }}
				</label>
			</p>
			<p>
				{{ form.verify.errors }}
				<label for="id_verify">
					{{ form.verify.label }}:<br>
					{{ form.verify }}
				</label>
			</p>
			<p>
				<input type="submit" value="Make Comment">
			</p>
		</form>
{% endblock %}

wiblog/templates/page-commented.html
{% extends "base-wiblog.html" %}


{% block title %}Comment Saved{% endblock %}


{% block content %}
		<header class="content-header">
			{% include "partial-nav.html" %}
			<h1>Comment Saved</h1>
			<p>
				Your feedback is important to me… unless you're a spam bot.
			</p>
		</header>
		<p>
			Hey, thanks for leaving me a comment. I really do appreciate that
			you took your time to leave me your thoughts.
		</p>
		<p>
			Unfortunately, I have to moderate them to prevent getting spammed 
			into oblivion. It should appear shortly.
		</p>
		<p>
			<a href="{% url "wiblog:index" %}">Home</a>
		</p>
{% endblock %}

wiblog/templates/page-post.html
{% extends "base-wiblog.html" %}


{% block title %}{{ post.title }}{% endblock %}


{% block content %}
		<header class="content-header">
			{% include "partial-nav.html" %}
			<h1>{{ post.formatted_title }}</h1>
			{% if post.subtitle %}
			<p>
				{{ post.subtitle }}
			</p>
			{% endif %}
			<p class="post-date">
				Posted on {{ post.date|date:"Y-m-d" }}
				{% if post.updated > post.date %}
				(Updated on {{ post.updated|date:"Y-m-d" }})
				{% endif %}
			</p>
		</header>
		{{ post.formatted }}
		{% if post.tags.all %}
		<p>
			Tags:
			{% for tag in post.tags.all %}
				<a href="{% url "wiblog:tagged" tag %}">{{ tag }}</a>
			{% endfor %}
		</p>
		{% endif %}
		{% if post.comment_set.count > 0 %}
		<hr>
		<h2>Comments</h2>
		{% for comment in post.comments|dictsortreversed:"date" %}
		<blockquote class="blog-comment">
			{{ comment.comment }}
			<p>
				<cite>
					{% firstof comment.name 'Anonymous' %}
					{% if comment.url %}
					 &ndash; {{ comment.url|urlize }}
					{% endif %}
				</cite>
			</p>
		</blockquote>
		{% endfor %}
		{% endif %}
		<hr>
		<h2 id="add-comment">Add Your Comment</h2>
		<form method="post" action="{% url "wiblog:comment" %}">
			{% csrf_token %}
			{{ comment_form.non_field_errors }}
			<p>
				{{ comment_form.post }}
				{{ comment_form.name.errors }}
				<label for="id_name">
					{{ comment_form.name.label }}:<br>
					{{ comment_form.name }}
				</label>
			</p>
			<p>
				{{ comment_form.url.errors }}
				<label for="id_url">
					{{ comment_form.url.label }}:<br>
					{{ comment_form.url }}
				</label>
			</p>
			<p>
				{{ comment_form.comment.errors }}
				<label for="id_comment">
					{{ comment_form.comment.label }}:<br>
					{{ comment_form.comment }}
				</label>
			</p>
			<p>
				{{ comment_form.verify.errors }}
				<label for="id_verify">
					{{ comment_form.verify.label }}:<br>
					{{ comment_form.verify }}
				</label>
			</p>
			<p>
				<input type="submit" value="Make Comment">
			</p>
		</form>
{% endblock %}

wiblog/templates/page-tagged.html
{% extends "base-wiblog.html" %}


{% block title %}Posts Tagged With '{{ tag }}'{% endblock %}


{% block content %}
		<header>
			{% include "partial-nav.html" %}
			<h1>Posts Tagged With <span class="tag">{{ tag }}</span></h1>
		</header>
		{% if tag.post_set.count > 0 %}
		<p>
			All of the following posts share a tag, and are related to that subject.
			If you would like to try another subject, you can pick from the
			available <a href="{% url "wiblog:tags" %}">tags</a>.
		</p>
		{% for post in tag.post_set.all|dictsortreversed:"date.year" %}

		<article>
			<h1>{{ post.formatted_title }}</h1>
			{{ post.formatted_summary }}
			<p>
				Read the full post: <a href=
				"{% url "wiblog:post" post.slug %}">{{ post.formatted_title }}</a>
			</p>
		</article>

		{% endfor %}
		{% else %}
		<p>
			There are currently no posts with this tag. Sorry!
		</p>
		<p>
			Luckily, you're not out of options. You can check out the <a href=
			"{% url "wiblog:archive" %}">archive</a> for other posts that may be of interest, or try
			another <a href="{% url "wiblog:tags" %}">tag</a>.
		</p>
		{% endif %}
{% endblock %}


{% block wiblog-ancillary %}
{% endblock %}

wiblog/templates/page-tags.html
{% extends "base-wiblog.html" %}


{% block title %}Tags{% endblock %}


{% block content %}
		<header class="content-header">
			<nav>
                <ul class="sub-nav">
                    <li><a class="nav-item" href="{% url "wiblog:archive" %}">Archive</a></li>
                    <li><a class="nav-item" href="{% url "wiblog:tags" %}">Tags</a></li>
                    <li><a class="nav-item" href="{% url "wiblog:rss" %}">RSS</a></li>
                    <li><a class="nav-item" href="{% url "wiblog:atom" %}">ATOM</a></li>
                </ul>
            </nav>
			<h1>Tags</h1>
			<p>
				A quick way to filter blog posts to only show a particular subject
			</p>
		</header>
			<p>
				Each blog post can be "tagged" with a subject. For example, a post
				about setting up a python application on an Apache web server could
				have the tags <span class="tag">python</span>, <span class=
				"tag">server</span>, and/or <span class="tag">apache</span>. You can
				use these tags to focus on posts that relate to a particular topic.
			</p>
			<p>
				Below are all of the tags found in post on this blog:
			</p>
			<ul class="tag-cloud">
				{% for tag in tags %}
					<li>
						<a href="{% url "wiblog:tagged" tag %}" class="tag">{{ tag }}</a>
					</li>
				{% endfor %}
			</ul>
{% endblock %}

wiblog/templates/partial-nav.html
			<nav>
                <ul class="sub-nav">
                    <li><a class="nav-item" href="{% url "wiblog:archive" %}">Archive</a></li>
                    <li><a class="nav-item" href="{% url "wiblog:tags" %}">Tags</a></li>
                    <li><a class="nav-item" href="{% url "wiblog:rss" %}">RSS</a></li>
                    <li><a class="nav-item" href="{% url "wiblog:atom" %}">ATOM</a></li>
                </ul>
            </nav>