fragdev/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib import admin
from fragdev import views

# Register admin pages
admin.autodiscover()

urlpatterns = [
    path('',
        views.HomeView.as_view(),
        name='home'),
    path('about/',
        views.AboutView.as_view(),
        name='about'),
    path('contact/',
        TemplateView.as_view(template_name="page-contact.html"),
        name='contact'),
    path('mei2019/',
        TemplateView.as_view(template_name="page-mei2019.html"),
        name='mei2019'
    ),
    path('minecraft/',
        TemplateView.as_view(template_name="page-minecraft.html"),
        name='minecraft'
    ),
    path('resume/',
        TemplateView.as_view(template_name="page-resume.html"),
        name='resume'
    ),
#    path('hire/',
#        TemplateView.as_view(template_name="page-hire.html"),
#        name='hire'
#    ),
    path('admin/', admin.site.urls),
]

# Set up some custom url patterns for debugging
if settings.DEBUG:
    # Append static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # Append media directory
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Blog URLs
if 'wiblog' in settings.INSTALLED_APPS:

    import wiblog.urls

    urlpatterns += [
        path('blog/', include(wiblog.urls)),
    ]	


# Dynamic image URLs
if 'images' in settings.INSTALLED_APPS:

    import images.urls

    urlpatterns += [
        path('img/', include(images.urls)),
    ]	


# Project URLs
if 'projects' in settings.INSTALLED_APPS:

    import projects.urls

    urlpatterns += [
        path('projects/', include(projects.urls)),
    ]	

images/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

# Placeholder urlpatterns list, in case views are added

app_name = 'images'

urlpatterns = []

projects/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='projects'),
    path('<slug>', views.project, name='project'),
]

wiblog/urls.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path 
from django.views.generic import TemplateView
from wiblog import feeds, views

app_name = 'wiblog'

urlpatterns = [
	path('archive/',
            views.ArchiveView.as_view(),
            name='archive'),
	path('comment/',
            views.CommentView.as_view(),
            name='comment'),
	path('comment-successful/',
            TemplateView.as_view(template_name="page-commented.html"),
            name='comment-successful'),
	path('feeds/atom/',
            feeds.PostFeedAtom(),
            name='atom'),
	path('feeds/rss/',
            feeds.PostFeedRSS(),
            name='rss'),
	path('tagged/<tag>/',
            views.TaggedPostView.as_view(),
            name='tagged'),
	path('tags/',
            views.TagsView.as_view(),
            name='tags'),
	path('<slug>',
            views.PostView.as_view(),
            name='post'),
	path('',
            views.IndexView.as_view(),
            name='index'),
]

projects/models.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models
from django.urls import reverse


class Project(models.Model):
    '''
    A project that I have contributed to, for display on the Projects page
    '''

    COMPLETED = 'com'
    DEVELOPMENT = 'dev'
    PRODUCTION = 'prd'
    HIDDEN = 'hid'
    PROJECT_STATUS = (
        (COMPLETED, 'Completed'),
        (DEVELOPMENT, 'In development'),
        (PRODUCTION, 'In Production'),
        (HIDDEN, 'Hidden'),
    )

    name = models.CharField('name', max_length=150)
    desc = models.TextField('description')
    short_desc = models.CharField('short description',
            max_length=300,
            blank=True)
    license = models.CharField('code license',
            max_length=50,
            blank=True)
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=3, choices=PROJECT_STATUS)
    github = models.URLField(blank=True)
    gitlab = models.URLField(blank=True)
    website = models.URLField(blank=True)
    example = models.URLField('example URL', blank=True)
    slug = models.SlugField(max_length=150)
    thumbnail = models.ForeignKey('images.Image',
            models.CASCADE,
            blank=True,
            null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("projects:project", args=[self.slug])

projects/views.py
# This file is part of the FragDev Website.
# 
# the FragDev Website is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# the FragDev Website is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the FragDev Website.  If not, see <http://www.gnu.org/licenses/>.

from commonmark import commonmark
from django.http import Http404, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.template import loader
from django.utils.safestring import mark_safe
from .models import Project


def index(request):
    '''
    Project listing
    '''

    projects = Project.objects.exclude(status=Project.HIDDEN).order_by('-date')
    template = loader.get_template('projects/page-index.html')

    return HttpResponse(template.render({'projects': projects}))


def project(request, slug):
    '''
    Display project details
    '''

    try:
        project = Project.objects.exclude(status=Project.HIDDEN).get(slug=slug)
    except ObjectDoesNotExist:
        raise Http404('Project "%s" does not exist' % slug)

    # Mark up the markdown in the project description
    project.desc = mark_safe(commonmark(project.desc))   
    
    template = loader.get_template('projects/page-project.html')

    return HttpResponse(template.render({'project': project}))

projects/templates/projects/page-index.html
{% extends "layout.html" %}
{% load static %}


{% block title %}Projects{% endblock %}


{% block head %}
	{{ block.super }}
	<link rel="stylesheet" type="text/css" href=
		"{% static "projects/css/projects.css" %}">
	<style>
	{% for project in projects %}
		{% if project.thumbnail %}
		#{{ project.slug }} {
			background-image: url('{{ project.thumbnail.get_absolute_url }}');
		}
		{% endif %}
	{% endfor %}
	</style>
{% endblock %}


{% block content %}
		<header class="content-header">
			<h1>Projects</h1>
			<p>
				A collection of the various projects I've worked on.
			</p>
		</header>
		<p>
			A good majority of the coding I do is in public.
			I'm on <a href="https://gitlab.com/u/windigo">Gitlab</a>, or
			<a href="https://github.com/lo-windigo">GitHub</a> where I'll
			try to mirror my repositories for those who prefer that service.
		</p>
		<ul class="project-thumbnails">
		{% for project in projects %}
			<li id="{{ project.slug }}">
				<a class="project-thumbnail" href=
				"{% url "projects:project" project.slug %}">
				<span>{{ project.name }}</span></a>
			</li>
		{% endfor %}
		</ul>
{% endblock %}

projects/templates/projects/page-project.html
{% extends "layout.html" %}
{% load static %}


{% block title %}{{ project.name }}{% endblock %}


{% block head %}
	{{ block.super }}
	<link rel="stylesheet" type="text/css" href=
		"{% static "projects/css/projects.css" %}">
{% endblock %}


{% block content %}
		<div class="project">
			<header class="content-header">
				<h1>{{ project.name }}</h1>
				{% if project.short_desc %}
				<p>
					{{ project.short_desc }}
				</p>
				{% endif %}
			</header>
			{% if project.thumbnail %}
			<figure class="project-image">
				<img src="{{ project.thumbnail.get_absolute_url }}"
					alt="A screenshot of {{ project.name }}">
			</figure>
			{% endif %}
			<dl class="project-meta">
				{% if project.status %}
					<dt>Status</dt>
					<dd>{{ project.get_status_display }}</dd>
				{% endif %}
				{% if project.license %}
					<dt>License</dt>
					<dd>{{ project.license }}</dd>
				{% endif %}
				{% if project.website %}
					<dt>Website</dt>
					<dd>
						<a href="{{ project.website }}">{{ project.website }}</a>
					</dd>
				{% endif %}
				{% if project.gitlab %}
					<dt>Gitlab</dt>
					<dd>
						<a href="{{ project.gitlab }}">{{ project.name }} on
						Gitlab</a>
					</dd>
				{% endif %}
				{% if project.github %}
					<dt>Github</dt>
					<dd>
						<a href="{{ project.github }}">{{ project.name }} on
						Github</a>
					</dd>
				{% endif %}
				{% if project.example %}
					<dt>Example</dt>
					<dd><a href="{{ project.example }}">{{ project.example }}</a></dd>
				{% endif %}
			</dl>
			{% if project.tags.all %}
			<p>
				Tags:
				{% for tag in project.tags.all %}
					<a href="{% url "project:tagged" tag %}">{{ tag }}</a>
				{% endfor %}
			</p>
			{% endif %}
			{% if project.desc %}
			<div class="project-details">
				{{ project.desc }}
			</div>
			{% endif %}
		</div>
{% endblock %}